CREATE TABLE IF NOT EXISTS investors (
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    identifier VARCHAR(64) UNIQUE,
    initial_investment DOUBLE PRECISION NOT NULL DEFAULT 0,
    shares DOUBLE PRECISION NOT NULL DEFAULT 0,
    current_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS holdings (
    id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    symbol VARCHAR(32),
    quantity DOUBLE PRECISION,
    cost_price DOUBLE PRECISION,
    market_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    weight DOUBLE PRECISION,
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fund_history (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    nav DOUBLE PRECISION NOT NULL,
    total_value DOUBLE PRECISION NOT NULL,
    change_pct DOUBLE PRECISION,
    change_value DOUBLE PRECISION,
    created_by_id INTEGER REFERENCES investors(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

